language: elixir

elixir:
  - '1.8.2'

env:
  - MIX_ENV=test

services:
  - docker

before_install:
  - docker pull lphoward/fake-s3
  - docker run -d -p 4569:4569 lphoward/fake-s3
  - docker ps -a

script:
  - mix format --check-formatted
  - mix compile --force --warnings-as-errors
  - mix coveralls.travis
