services:
  minio:
    image: minio/minio:RELEASE.2020-10-18T21-54-12Z
    command: ["server", "/data"]
    ports: ["9000:9000"]
    environment:
      MINIO_ACCESS_KEY: development
      MINIO_SECRET_KEY: development
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
