name: Build
on: [push]
jobs:
  # Lint should only run against the latest versions.
  lint:
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: dev
    name: Lint
    strategy:
      matrix:
        os: ["ubuntu-20.04"]
        elixir: ["1.13"]
        otp: ["24"]
    steps:
      - uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v2
        with:
          path: deps
          key: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_
      - run: mix deps.get
      - run: mix deps.compile
      - run: mix format --check-formatted
      - run: mix deps.unlock --check-unused
      - name: Cache dialyzer
        uses: actions/cache@v2
        with:
          path: priv/plts
          key: plts-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}
      - name: Dialyzer
        run: mix dialyzer
      - name: Credo
        run: mix credo --all
  # Build phase to check against multiple versions of OTP and elixir for as
  # much compatibility as we can stand.
  build:
    runs-on: ${{ matrix.os }}
    env:
      MIX_ENV: test
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    name: Test Elixir ${{ matrix.elixir }}, OTP ${{ matrix.otp }}, OS ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: ["ubuntu-20.04"]
        elixir: ["1.13", "1.12", "1.11", "1.10"]
        otp: ["24", "23", "22"]
    services:
      minio:
        image: rzane/minio
        ports: ["9000:9000"]
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - uses: erlef/setup-beam@v1
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - uses: actions/cache@v2
        with:
          path: deps
          key: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_${{ hashFiles('**/mix.lock') }}
          restore-keys: ${{ matrix.os }}-otp_${{ matrix.otp }}-elixir_${{ matrix.elixir }}-mix_
      - name: Dependencies
        run: mix deps.get --only test
      - name: Compile
        run: mix compile --force --warnings-as-errors
      - name: Test
        run: mix coveralls.github
