name: Publish
on:
  release:
    types: [published]
jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Elixir
        uses: erlef/setup-beam@v1
        with:
          otp-version: "24"
          elixir-version: "1.13"

      - name: Dependencies
        run: mix deps.get

      - name: Publish
        run: bin/publish "${GITHUB_REF:11}"
        env:
          HEX_API_KEY: ${{ secrets.HEX_TOKEN }}
